rails/config/routes.rb
Rails.application.routes.draw do











  
  resources :fellowships, except: [:new, :edit]
  resources :fellows, except: [:new, :edit]
  resources :fellows

  get '*path', to: 'home#index'
end

rails/app/models/fellow.rb
class Fellow < ActiveRecord::Base
end

rails/app/models/fellowship.rb
class Fellowship < ActiveRecord::Base
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/app/controllers/fellows_controller.rb
class FellowsController < ApplicationController
  before_action :set_fellow, only: [:show, :update, :destroy]

  # GET /fellows
  # GET /fellows.json
  def index
    @fellows = Fellow.all

    render json: @fellows
  end

  # GET /fellows/1
  # GET /fellows/1.json
  def show
    render json: @fellow
  end

  # POST /fellows
  # POST /fellows.json
  def create
    @fellow = Fellow.new(fellow_params)

    if @fellow.save
      render json: @fellow, status: :created, location: @fellow
    else
      render json: @fellow.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /fellows/1
  # PATCH/PUT /fellows/1.json
  def update
    @fellow = Fellow.find(params[:id])

    if @fellow.update(fellow_params)
      head :no_content
    else
      render json: @fellow.errors, status: :unprocessable_entity
    end
  end

  # DELETE /fellows/1
  # DELETE /fellows/1.json
  def destroy
    @fellow.destroy

    head :no_content
  end

  private

    def set_fellow
      @fellow = Fellow.find(params[:id])
    end

    def fellow_params
      params.require(:fellow).permit(:image, :name, :nonprofit, :benefactor, :employer, :metro, :cohort)
    end
end

rails/app/controllers/fellowships_controller.rb
class FellowshipsController < ApplicationController
  before_action :set_fellowship, only: [:show, :update, :destroy]

  # GET /fellowships
  # GET /fellowships.json
  def index
    @fellowships = Fellowship.all

    render json: @fellowships
  end

  # GET /fellowships/1
  # GET /fellowships/1.json
  def show
    render json: @fellowship
  end

  # POST /fellowships
  # POST /fellowships.json
  def create
    @fellowship = Fellowship.new(fellowship_params)

    if @fellowship.save
      render json: @fellowship, status: :created, location: @fellowship
    else
      render json: @fellowship.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /fellowships/1
  # PATCH/PUT /fellowships/1.json
  def update
    @fellowship = Fellowship.find(params[:id])

    if @fellowship.update(fellowship_params)
      head :no_content
    else
      render json: @fellowship.errors, status: :unprocessable_entity
    end
  end

  # DELETE /fellowships/1
  # DELETE /fellowships/1.json
  def destroy
    @fellowship.destroy

    head :no_content
  end

  private

    def set_fellowship
      @fellowship = Fellowship.find(params[:id])
    end

    def fellowship_params
      params.require(:fellowship).permit(:title, :fellow_id)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/fellows_helper.rb
module FellowsHelper
end

rails/app/views/fellows/_form.html.erb
<%= form_for(@fellow) do |f| %>
  <% if @fellow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fellow.errors.count, "error") %> prohibited this fellow from being saved:</h2>

      <ul>
      <% @fellow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nonprofit %><br>
    <%= f.text_field :nonprofit %>
  </div>
  <div class="field">
    <%= f.label :benefactor %><br>
    <%= f.text_field :benefactor %>
  </div>
  <div class="field">
    <%= f.label :employer %><br>
    <%= f.text_field :employer %>
  </div>
  <div class="field">
    <%= f.label :metro %><br>
    <%= f.text_field :metro %>
  </div>
  <div class="field">
    <%= f.label :cohort %><br>
    <%= f.text_field :cohort %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/fellows/edit.html.erb
<h1>Editing fellow</h1>

<%= render 'form' %>

<%= link_to 'Show', @fellow %> |
<%= link_to 'Back', fellows_path %>

rails/app/views/fellows/index.html.erb
<h1>Listing fellows</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Nonprofit</th>
      <th>Benefactor</th>
      <th>Employer</th>
      <th>Metro</th>
      <th>Cohort</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fellows.each do |fellow| %>
      <tr>
        <td><%= fellow.image %></td>
        <td><%= fellow.name %></td>
        <td><%= fellow.nonprofit %></td>
        <td><%= fellow.benefactor %></td>
        <td><%= fellow.employer %></td>
        <td><%= fellow.metro %></td>
        <td><%= fellow.cohort %></td>
        <td><%= link_to 'Show', fellow %></td>
        <td><%= link_to 'Edit', edit_fellow_path(fellow) %></td>
        <td><%= link_to 'Destroy', fellow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fellow', new_fellow_path %>

rails/app/views/fellows/new.html.erb
<h1>New fellow</h1>

<%= render 'form' %>

<%= link_to 'Back', fellows_path %>

rails/app/views/fellows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @fellow.image %>
</p>

<p>
  <strong>Name:</strong>
  <%= @fellow.name %>
</p>

<p>
  <strong>Nonprofit:</strong>
  <%= @fellow.nonprofit %>
</p>

<p>
  <strong>Benefactor:</strong>
  <%= @fellow.benefactor %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @fellow.employer %>
</p>

<p>
  <strong>Metro:</strong>
  <%= @fellow.metro %>
</p>

<p>
  <strong>Cohort:</strong>
  <%= @fellow.cohort %>
</p>

<%= link_to 'Edit', edit_fellow_path(@fellow) %> |
<%= link_to 'Back', fellows_path %>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ga</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>